# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs: 

- job: Linux
  displayName: 'Building on Linux'
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
    
- job: macOS
  displayName: 'Building on MacOS'
  pool:
    vmImage: 'macOS-latest'
  variables:
    buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
    
- job: Windows
  displayName: 'Building on Windows'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
  steps:
    - script: dotnet build --configuration $(buildConfiguration)
    - script: dotnet test --configuration $(buildConfiguration) --filter "PrtSharpRegressionTests"




